import { ClassGroup } from "@/types";

export const classGroup: ClassGroup[] = [
  {
    name: "BeautyTok",
    prompts: [
      "makeup",
      "skincare",
      "cosmetic product",
      "doing nails",
      "doing hair",
      "eyeshadow",
      "lipstick",
      "blush",
    ],
  },
  {
    name: "DanceTok",
    prompts: [
      "dance tutoria",
      "dance competition",
      "dance challenge",
      "dance trend",
      "dance with friends",
      "dance class",
      "dance moves",
      "dance lessons",
      "dance choreography",
      "dance performances",
    ],
  },
  {
    name: "CookTok",
    prompts: [
      "cookint tutorial",
      "cooking utensils",
      "baking utensils",
      "recipes",
      "restaurants",
      "food",
      "cooking tips",
      "cooking techniques",
      "healthy cooking",
    ],
  },
  {
    name: "animalTok",
    prompts: [
      "dog",
      "cat",
      "birds",
      "fish",
      "playing with pets",
      "fish",
      "feeding pets",
      "caring for animals",
    ],
  },
  {
    name: "KidTok",
    prompts: [
      "babies",
      "little girl",
      "little boy",
      "kids",
      "toddlers",
      "children",
      "animation",
      "kid toys",
    ],
  },
  {
    name: "FashionTok",
    prompts: [
      "clothing",
      "outfit",
      "fashion design",
      "mens fashion",
      "womens fashion",
      "find your style",
      "upcoming fashion trends",
      "streetwear",
      "style advide",
    ],
  },
  {
    name: "ArtTok",
    prompts: [
      "handicraft",
      "drawing",
      "graffiti",
      "sketching",
      "digital art",
      "sketchbook",
      "artists",
      "artwork",
      "painting",
    ],
  },
  {
    name: "FitTok",
    prompts: [
      "doing exercises",
      "workout",
      "being active",
      "staying active",
      "personal trainer",
      "going to the gym",
      "weight training",
      "yoga",
    ],
  },
];
